# -*- coding: utf-8 -*-
"""AI_exam08_classification_fashion_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHvYjrOTlSa7fLsX6tpQp9d_teSSAIvP
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Flatten
from keras.utils import to_categorical

(X_train,Y_train),(X_test,Y_test) = fashion_mnist.load_data()
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)   #6만장 28*28사이즈의 이미지
print(Y_test.shape)

my_sample= np.random.randint(0,X_train.shape[0])  #랜덤값 뽑는다.
print(my_sample)   #3455
print(Y_train[my_sample])  #4
plt.imshow(X_train[my_sample],cmap='gray')
plt.show()
print(X_train[my_sample])

label = ['T-shirt', 'trouser', 'pullover', 'dress', 'coat', 'sandal', 'shirt', 'sneaker', 'bag', 'ankle_boot']

y_train = to_categorical(Y_train)
y_test= to_categorical(Y_test)
print(y_train.shape)
print(y_test.shape)
print(y_train[my_sample])

"""판다스 겟 더미스 사이킷런의 원핫코드 캐라스 투카테고리컬"""

x_train = X_train.reshape(60000,28, 28, 1)  #shape가 바뀌었다.
x_test = X_test.reshape(10000,28, 28, 1)
print(x_train[5000])
print(X_train[5000])

"""입력데이터 스케일링"""

x_train = x_train/255
x_test = x_test/255
print(x_train.shape)
print(x_train[5000])   #스케일링이 1이 넘어가지 않도록

model =Sequential()
model.add(Conv2D(32,input_shape=(28, 28, 1), activation = 'relu', kernel_size=(3,3), padding ='same'))
model.add(MaxPooling2D(pool_size=(2,2), padding = 'same'))
model.add(Conv2D(32, activation = 'relu', kernel_size=(3,3), padding ='same'))
model.add(MaxPooling2D(pool_size=(2,2), padding = 'same'))
model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))
model.summary()

"""총 32개의 커널 커널 사이즈는 3*3 , 패딩은 same \
input_size는 2차원으로 만들어 주어야 한다. 그림의 특징을 파악하기 위해. \
1차원으로 하면 원하는 결과가 잘 안나온다. ex)784
바이어스는 필터하나당 하나씩 weight는 한필터당 9개 \
32*(9+1) =320 파라미터 개수는 덴스 레이어보다 적지만 여러개를 해야하기 때문에 계산량이 많아진다. \
maxpool은 이미지중에 가장 큰값 남겨놓음 -이미지 특성만 남음, 잡음 사라짐, 이미지 작아짐
maxpool은 건너띄고 겹치지 않음
"""

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

fit_hist = model.fit(x_train, y_train, epochs= 15, batch_size=512,validation_split=0.2)

plt.plot(fit_hist.history['loss'], label= 'Training_Loss')
plt.plot(fit_hist.history['val_loss'], label= 'Validation_Loss')
plt.legend()
plt.show()

plt.plot(fit_hist.history['accuracy'], label= 'Training_Accuracy')
plt.plot(fit_hist.history['val_accuracy'], label= 'Validation_Accuracy')
plt.legend()
plt.show()

score= model.evaluate(x_test,y_test)
print('Final test set accuracy', score[1])

my_sample = np.random.randint(0,X_test.shape[0])
print('actual',Y_test[my_sample], label[Y_test[my_sample]])
pred = model.predict(x_test[my_sample].reshape(1,28,28,1))
print(pred)
print('predict', np.argmax(pred), label[np.argmax(pred)])
plt.imshow(X_test[my_sample], cmap='gray')
plt.show()

# !pip list
#
# !python --version

