# -*- coding: utf-8 -*-
"""AI_exam07_classification_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYakvRy5yn1r1B9FyS_VKzRlFB8OnguS
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical

(X_train,Y_train),(X_test,Y_test) = mnist.load_data()
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)   #6만장 28*28사이즈의 이미지
print(Y_test.shape)

my_sample= np.random.randint(0,X_train.shape[0])  #랜덤값 뽑는다.
print(my_sample)   #3455
print(Y_train[my_sample])  #4
plt.imshow(X_train[my_sample],cmap='gray')
plt.show()
print(X_train[my_sample])

y_train = to_categorical(Y_train)
y_test= to_categorical(Y_test)
print(y_train.shape)
print(y_test.shape)
print(y_train[my_sample])

"""판다스 겟 더미스 사이킷런의 원핫코드 캐라스 투카테고리컬"""

x_train = X_train.reshape(60000,784)  #shape가 바뀌었다.
x_test = X_test.reshape(10000,784)
print(x_train[5000])
print(X_train[5000])

"""입력데이터 스케일링"""

x_train = x_train/255
x_test = x_test/255
print(x_train.shape)
print(x_train[5000])   #스케일링이 1이 넘어가지 않도록

model =Sequential()
model.add(Dense(128, input_shape = (784,), activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))
model.summary()

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

fit_hist = model.fit(x_train, y_train, epochs= 15, batch_size=512,validation_split=0.2)

plt.plot(fit_hist.history['loss'], label= 'Training_Loss')
plt.plot(fit_hist.history['val_loss'], label= 'Validation_Loss')
plt.legend()
plt.show()

plt.plot(fit_hist.history['accuracy'], label= 'Training_Accuracy')
plt.plot(fit_hist.history['val_accuracy'], label= 'Validation_Accuracy')
plt.legend()
plt.show()

score= model.evaluate(x_test,y_test)
print('Final test set accuracy', score[1])

