# -*- coding: utf-8 -*-
"""AI_exam03_keras_xor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ano4v8CXyQzj-eBGV77sCENaU5CW5JzI

https://itwiki.kr/w/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5
"""

import numpy as np
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.pyplot as plt

training_data = np.array([[0,0],[0,1],[1,0],[1,1]])            #ANDgate
target_data = np.array([[0],[0],[0],[1]])

from keras.src.losses import loss
model = Sequential()
model.add(Dense(32,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='mse',optimizer='adam',metrics=['binary_accuracy'])
model.summary()

fit_hist = model.fit(training_data,target_data ,epochs =500 ,verbose=1)

print(model.predict(np.array([[1, 1]])).round())

plt.plot(fit_hist.history['loss'])
plt.show()

training_data1 = np.array([[0,0],[0,1],[1,0],[1,1]])            #ANDgate
target_data1 = np.array([[0],[1],[1],[0]])

from keras.src.losses import loss
model = Sequential()
model.add(Dense(32,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='mse',optimizer='adam',metrics=['binary_accuracy'])
model.summary()

fit_hist = model.fit(training_data1,target_data1 ,epochs =500 ,verbose=1)

