# -*- coding: utf-8 -*-
"""AI_exam06_iris_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ox6uQ_ykU4xl_eN7SGDbCNS96JCq-3ms

##다중분류기
3가지 품종의 붓꽃
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

iris= load_iris()
print(type(iris))
print(iris.keys())

iris.data.shape

iris.feature_names

iris.target  #품종별로 50개씩 들어가 있다.

iris.target_names

iris_dataframe= pd.DataFrame(iris.data, columns=iris.feature_names)
iris_dataframe.head()

pd.plotting.scatter_matrix(iris_dataframe,c=iris.target,figsize=(8,8),s=20,marker='o',alpha=0.3)
plt.show()

x = iris.data
y = iris.target.reshape(-1,1)
print(x.shape)
print(y.shape)

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output= False) #희소 영역
encoded_y = encoder.fit_transform(y)
print(encoded_y)

"""다중분류기 이중분류기"""

X_train,X_test, y_train,y_test = train_test_split(x,encoded_y,test_size=0.2)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

model= Sequential()
model.add(Dense(10, input_shape=(4,),activation='relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(3, activation='softmax'))  #확률값으로 바꿔줌. 모든 확률의 합이 1이다.
model.compile(optimizer='adam', loss= 'categorical_crossentropy',metrics=['accuracy'])
model.summary()

fit_hist = model.fit(X_train,y_train, epochs= 30, batch_size = 32, validation_data=(X_test, y_test))

plt.plot(fit_hist.history['accuracy'])
plt.plot(fit_hist.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

score = model.evaluate(X_test,y_test)
print(score)

